### ISSUE TITLE
Running Get-Remote more than once from same Powershell Session crashes.

### ISSUE THREAD

**Issue by bobsupercow** [onyx-and-iris/voicemeeter-api-powershell#2] opened 2021-11-03 17:17 UTC
Running Get-Remote Multiple times from same Powershell Session crashes. 
This happens with all types Basic, Banana, Potato. 

Found while running my own script multiple times in Powershell, which gave me error: 
```powershell
You cannot call a method on a null-valued expression.
At D:\Downloads\test.ps1:22 char:1
+ $vmr.Logout()
+ ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
```powershell
#Test Script
Import-Module Voicemeeter
try {
    # Run the factory function for required Voicemeeter type
    $vmr = Get-RemotePotato
#Do other stuff here in my script
}
finally { 
$vmr.Logout() 
}
```

Attempts to narrow it down with try/catch blocks in Get-Remote and constructor methods were unsuccessful. It crashes the whole Powershell window. 

- Wrapping contents of Get-Remote function in try/catch. 
- Wrapping contents of Remote constructor in try/catch.

**Comment by onyx-and-iris** [comment] 2021-11-03 20:00
Hello, this issue arises due to the fact that Logout() is called on the vmr object in the finally block. The voicemeeter api was designed such that login is called once at the start and logout once at the end of the code. I'm not sure what your intended use with this wrapper is but perhaps you can try calling the Get-Remote function outside of a try/finally block, using the vmr object however many times you need and then manually invoking logout when you need to.

You wouldn't want to call Get-Remote functions multiple times without first logging out since that would lead to undefined behaviour. Being unable to login after logout, however, is a limitation of the API rather than this wrapper, as that is how the developer intended it be interacted with.

I hope that is helpful.

**Comment by bobsupercow** [comment] 2021-11-04 03:17
Confirmed by modifying Voicemeeter.psm1 as follows:
```powershell
    [void] Setup() {
        if(Setup_DLL) {
            #Login -TYPE $this.type

            $this.button = Buttons
            $this.strip = Strips
            $this.bus = Buses
            $this.vban_in = Vban_In
            $this.vban_out = Vban_Out
            $this.command = Special
        }
        else { Exit }
    }
	
	[void] Login() {
        try{
            Login -TYPE $this.type
	}
	catch{
	    Write-Output $PSItem.ToString
	}
    }
```
This allows me to setup a Remote Object and independently call Login. Multiple calls to Login from same remote object cause the same crash. With no error thrown.
```powershell
$vmr = Get-RemotePotato
$vmr.Login() #Works As Expected
$vmr.Logout() #Works As Expected
$vmr.Login() #Fails.
```

From VBVMR-API: 

>  Again Login function must be called once by the user application, for all its duration life.  

> IMPORTANT REM: Call VBVMR_Logout()once at the end of the program. 

Maybe I'm just misunderstanding this implementation. I initially thought that meant any call to VBVMR_Login() **MUST** have a corresponding VBVMR_Logout(). 

But maybe it's actually that any process loading the .dll is allowed to make only **1 total** call to VBVMR_Login().  Since I can run two independent Powershell instances logging in independently with no issues. 

If so that's not very clear.  If that's the case, what's the point of the Logout Function? 
Shouldn't it at minimum throw an exception? 
Any idea the proper channel to contact their dev team? 

Thanks for the prompt response. 


For my current implementation I can use try/catch/finally and check if $vmr -eq $null, which prevents the whole window from crashing, but I still have to create a new Powershell session for each test. 

It was only really a problem since I was making changes to code quickly. By default, when I called my .ps1 from within a Powershell window, the instance of your wrapper is tied to my window's process. So I could not call it again from that window. 

Easy fix was to either invoke a new window while testing via a helper .vbs script. 

Implementation is a simple script to toggle the currently unmuted bus and display an overlay showing which bus is active on the primary display. Will share when completed in case you want to add it to the examples.

**Comment by onyx-and-iris** [comment] 2021-11-04 08:44
Hi again mate. Yes I do believe what you are saying is correct, that a program loading the dll is meant to login and logout a single time. I don't know why the api was developed with this limitation, the best way to contact the developer is through the voicemeeter discord. https://discord.com/invite/TF42rahAXS

I assume logout is required to ensure the connection is closed correctly, in the case as you mentioned that more than a single external program is logging in and out of the api. Perhaps they don't know about each other, so to speak.

You may check page 7 of the documentation for further explanation regarding login/logout:
https://download.vb-audio.com/Download_CABLE/VoicemeeterRemoteAPI.pdf

The login function does return a value but doesn't throw an exception I believe. If you check line 250 in base.ps1:
$retval = [Int][Voicemeeter.Remote]::VBVMR_Login()
So I think a return value could be used to generate and throw an exception object in this case, to make things more clear.

Thank you for your interest in this code and by all means feel free to share any code/examples. Pull requests are welcome.

**Comment by bobsupercow** [comment] 2021-11-04 09:51
Attached Below. It could use some cleanup, but functional for now, and good enough for my use case. Most of the code is UI stuff, relevant VM code below:
```powershell
#Loops through buses included in $buses array, looking for 1st unmuted bus. Toggles mute on that bus, then unmutes the next bus in the array. If there is no next bus in the array, mute the first bus. 
#Combined with a .vbs to call without a window pop-up, you can have a hotkey to "Go to Next Bus" in a subset of buses with a visual Indicator on your primary display. 
# Run the factory function for required Voicemeeter type
$vmr = Get-RemotePotato
$unmutedIndex = 0
#This could be any combination of buses. e.g. (0,3; 0,1,4,5; 1,3,5)
[int32[]]$buses = 0,1,2
for(($i=0); $i -le ($buses.Length -1); $i++){
if ($vmr.bus[$buses[$i]].mute -eq $false){
	#Found 1st unmuted bus. Mute it. 
	$vmr.bus[$buses[$i]].mute = $true
          $unmutedIndex = $i+1
	if ($i -lt ($buses.Length -1)){
		#Unmute the next bus. 
		$vmr.bus[$buses[$i+1]].mute = $false
		#exit the loop
		break
	}
	elseif ($i -eq ($buses.Length -1)){
		#Unmute the first bus.
		$vmr.bus[0].mute = $false
              $unmutedIndex = 0
		#exit the loop
		break
	}

}
```

Includes the .ps1 and a helper .vbs which is useful to use with Hotkey applications since it will launch the Powershell script without opening a window/flicker like it would if opened directly. 

[ToggleVMDevice.zip](https://github.com/onyx-and-iris/voicemeeter-api-powershell/files/7473804/ToggleVMDevice.zip)

**Comment by onyx-and-iris** [comment] 2021-11-05 10:14
Ok thank you for your contribution! I'll take a look over it later. I will close this ticket for now. Feel free to open another issue if you have further questions.

**Closed by onyx-and-iris** 2021-11-05 10:14 UTC
